# Generated by Django 3.1.2 on 2021-12-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0002_alter_tripulantes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripulantes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
